# docker-compose.yml
version: '3.8'

services:
  web:
    build: ./src # Construye la imagen Docker desde el directorio 'src'
    ports:
      - "5001:5001" # Mapea el puerto 5000 del contenedor al puerto 5000 de tu máquina
    environment:
      # Variables de entorno para la conexión a la base de datos
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    depends_on:
      - db # Asegura que el servicio 'db' se inicie antes que 'web'
    restart: on-failure # Reinicia el contenedor si falla
    networks:
      - app-network # Conecta al servicio 'db' a través de esta red

  db:
    image: mysql:8.0 # Utiliza la imagen oficial de MySQL versión 8.0
    environment:
      # Variables de entorno para la configuración de MySQL
      MYSQL_ROOT_PASSWORD: root_password # Contraseña del usuario root de MySQL
      MYSQL_DATABASE: mydatabase # Nombre de la base de datos a crear
      MYSQL_USER: user # Nombre de usuario para la base de datos
      MYSQL_PASSWORD: password # Contraseña para el usuario de la base de datos
    volumes:
      - db_data:/var/lib/mysql # Persistencia de datos para la base de datos
    ports:
      - "3306:3306" # Mapea el puerto 3306 del contenedor al puerto 3306 de tu máquina (opcional, para acceso externo)
    networks:
      - app-network # Conecta al servicio 'web' a través de esta red

# Define los volúmenes para la persistencia de datos
volumes:
  db_data:

# Define la red para que los servicios puedan comunicarse entre sí
networks:
  app-network:
    driver: bridge
